services:
  db:
    image: postgres:17
    container_name: forwardoo_db
    ports:
      - 54322:5432
    environment:
      POSTGRES_DB: forwardoo
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data:rw
    restart: always
    networks:
      - forwardoo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 100

  php:
    container_name: forwardoo_php
    command: >
      /bin/sh -c "composer install && php-fpm"
    build: .
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - forwardoo
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: forwardoo_nginx
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - php
    networks:
      - forwardoo

networks:
  forwardoo:
    name: forwardoo

volumes:
  database:
